export {default as FirstScreen} from './First';
export {default as Login} from './auth/Login';
export {default as Register} from './auth/Register';
export {default as ConfirmCode} from './auth/ConfirmCode';
export {default as NameInput} from './auth/NameInput';
export {default as BirthdayInput} from './auth/BirthdayInput';
export {default as LocationInput} from './auth/LocationInput';
export {default as UserDashBoard} from './user/DashBoard.user';
export {default as UserSetting} from './user/Setting.user';
